semaphoreci/cli

cmd/utils/editor.go, config/config.go
Two changes in this PR:
1. The order of editor lookup: (1) try from config, (2) try from EDITOR env var, (3) use vim
2. Editor can now have additional flags, example: `subt --something`.
Supporting flags in editor command wasn't straghtforward, but I found a solution in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/editor/editor.go#L70.
fixes https://github.com/semaphoreci/cli/issues/130
fixes https://github.com/semaphoreci/cli/issues/132
=> Editor env var; Editor arguments

.goreleaser.yml
The [previous attempt](https://github.com/semaphoreci/cli/pull/147) doesn't work, example with edge release:
My guess is bc we are trying to change the `VERSION` in the main package, as we do in agent. However, here the `VERION` lives in the cmd package, in a separate file: https://github.com/semaphoreci/cli/blob/master/cmd/version.go#L9
Not sure if goreleaser can access other packages than main, though. :thinking:
=> Adjust correct version variable with goreleaser

api/client/base_client.go, api/client/jobs_v1_alpha.go, api/models/job_debug_ssh_key_v1_alpha.go, api/models/job_v1_alpha.go, cmd/attach.go, cmd/debug_job.go, cmd/debug_project.go, cmd/ssh/connection.go, cmd/ssh/session.go, config/config.go
Updates that this PR brings:
- SSH sessions work without configuring the CLI with an SSH key
- Customers can attach to any Job without the need to inject public keys into the job
- Debugging and Attaching works for Docker based CI/CD environments
=> Debug sessions with Sempahore generated keys

cmd/ssh/connection.go
A customer reported that he is not able to start a debug session, and that he sees the following error message in his output:
```
$ sem attach <job-id>                                                                                                                                                                                       
Warning: Permanently added '[<ip>]:<port>' (RSA) to the list of known hosts.
Received disconnect from <ip> port <port>:2: Too many authentication failures
Disconnected from <ip> port <port>
```
**Root Cause of Too many authentication failures**
The most common cause of this issue is if you have multiple keys set up on your machine, and you breach the `MaxAuthTries` configuration on the server. The default value of this is set to `6`, in other words, if you …
=> Establish SSH connection with IdentitiesOnly flag set to "yes"

cmd/ssh/connection.go
A race condition can occur when we are starting an SSH session. We can jump into the machine _before_ the toolbox commands have completed.
Now, that the backend is creating a marker for us, we can use that marker to check if it is safe to jump into the machine.
=> Wait for user commands to start

api/models/project_v1_alpha.go, cmd/apply_test.go, cmd/create_test.go, cmd/init.go, cmd/init_test.go
Adds a new `--integration-type` parameter to the `sem init` command. The possible values are `github_token` (default) and `github_app`. The project API already accepts this parameter, so no changes were required in the API.
=> feat: add integration-type argument on sem init

CHANGELOG.md, Makefile
Also, updates the `gsutil.configure` Makefile target to use proper `--quiet` flag.
=> docs: update CHANGELOG.md

api/client/agent_types_v1_alpha.go, api/models/agent_type_list_v1_alpha.go, api/models/agent_type_v1_alpha.go, cmd/create.go, cmd/create_test.go, cmd/delete.go, cmd/delete_test.go, cmd/get.go, cmd/get_test.go
Adds the operations for the new v1alpha API for self-hosted agent types.
=> feat: list/get/create/delete operations for agent_type resource

api/client/project_secrets_v1.go, api/models/project_secret_list_v1.go, api/models/project_secret_v1.go, cmd/apply.go, cmd/create.go, cmd/delete.go, cmd/edit.go, cmd/get.go
Adds project level secrets to sem cli
it extends the CLI for secrets from:
```
sem get secrets
sem get secret [name]
sem edit secret [name]
sem apply [-f yaml_file]
sem create secret [name]
sem delete secret [name]
```
to now have a optional flag `--project-name` or `--project-id` 
```
sem get secrets --project-name[--project-id] [project_id_or_name]
sem get secret --project-name[--project-id] [project_id_or_name] [name]
sem edit secret [name] --project-name[--project-id] [project_id_or_name]
sem apply [-f yaml_file]
sem create secret -f yaml_file
sem delete secret [name] --project-name[--project-id] [project_id_or_name]
```
when this flag is present we are going to project level secrets.
For apply and create there is new resource kind `ProjectSecret` to distinguish from organization …
=> Add project level secrets

api/client/troubleshoot_v1_alpha.go, api/models/troubleshoot_v1_alpha.go, cmd/troubleshoot.go
Adds a new `sem troubleshoot` command, which assists customers when opening support cases (especially for on-premise installations). The command has three sub-commands:
- `sem troubleshoot job JOB_ID`
- `sem troubleshoot pipeline PIPELINE_ID`
- `sem troubleshoot workflow WORKFLOW_ID`
This makes it easy for a customer to provide all the information required to troubleshoot things from our side.
=> feat: add troubleshoot command

api/client/agent_v1_alpha.go, api/models/agent_list_v1_alpha.go, api/models/agent_v1_alpha.go, cmd/get.go, cmd/get_test.go
Adds a new get command to list/describe self-hosted agents:
```
» sem get agents
NAME       TYPE         STATE           AGE
my-agent-1 s1-aws-small waiting_for_job 12m
my-agent-2 s1-aws-small waiting_for_job 10m
my-agent-3 s1-aws-small running_job      8m
my-agent-3 s1-aws-large waiting_for_job  1m
» sem get agent my-agent-1
apiVersion: v1alpha
kind: SelfHostedAgent
metadata:
name: my-agent-1
type: s1-aws-small
connected_at: 1686789756
version: v2.2.6
os: Ubuntu 22.04
arch: x86_64
hostname: agenthostname
ip_address: 0.0.0.0
pid: 0
status:
state: waiting_for_job
```
=> feat: self-hosted agent get/list command

api/client/agent_types_v1_alpha.go, api/models/agent_type_list_v1_alpha.go, api/models/agent_type_v1_alpha.go, cmd/apply.go, cmd/apply_test.go, cmd/create.go, cmd/create_test.go, cmd/utils/slices.go, cmd/utils/slices_test.go
This pull request adds a spec field to the agent type model. For now, the spec will only contain an `agent_name_settings` field, with the following properties:
- `assignment_origin`: a string to specify if agents will have their names assigned by AWS STS (`assignment_origin_aws_sts`) or by themselves (`assignment_origin_agent`). The default is `assignment_origin_agent`.
- `release_after`: number of seconds to hold the agent name after its disconnection. By default, this is 0.
- `aws`: an object field to specify the `account_id` and `role_name_patterns` when `assignment_origin_aws_sts` is used.
Here's an example of an agent type with `assignment_origin_agent`:
```yaml
apiVersion: v1alpha
kind: SelfHostedAgentType
metadata:
name: s1-testing
create_time: 1700679079
update_time: 1700679079 …
```
=> feat: add support for agent type name settings

Makefile
When building with `make build` the `sem` binary isn't able to report the version:
```
make build && ./sem version
env GOOS= GOARCH= go build -ldflags "-s -w -X cmd.VERSION=v0.28.3" -o sem
tar -czvf /tmp/sem.tar.gz sem
sem
dev, commit none, built at unknown
```
After this fix it is:
```
make build && ./sem version
env GOOS= GOARCH= go build -ldflags "-s -w -X main.version=v0.28.3" -o sem
tar -czvf /tmp/sem.tar.gz sem
sem
v0.28.3, commit none, built at unknown
```
=> Fix version when building with Makefile

cmd/create_secret.go, cmd/create_secret_test.go
Allows users to create a project level secret with `sem create secret` by specifying `-p` or `-i` flags with project ID or Name. The file and env var parsing is separated into two functions as it is the simples approach.
=> Add project secret create to sem create secret

api/client/project_secrets_v1.go, api/client/secrets_v1_beta.go, api/models/project_secret_v1.go, api/models/secret_v1_beta.go, cmd/apply.go, cmd/edit.go, cmd/utils/ask_confirm.go
- Show secrets without contents nicely
- If update fails (which will happen when secret's contents can not be fetched) the cli will remove existing secret and recreate it with new contents.
task: https://github.com/renderedtext/project-tasks/issues/1284
=> Handle secrets without contents

cmd/apply.go, cmd/apply_test.go, cmd/edit.go, cmd/edit_test.go, cmd/utils/ask_confirm.go
`gosec` reporting `G101: Potential hardcoded credentials` is a false positive.
task: https://github.com/renderedtext/project-tasks/issues/1284
regression made in: https://github.com/renderedtext/project-tasks/issues/1284
=> Add false positive exceptions

api/client/logs_v1_alpha.go, api/models/logs_v1_alpha.go, cmd/edit.go, cmd/logs.go, cmd/logs_test.go
https://github.com/renderedtext/project-tasks/issues/1285
Refactor the logs command to use the newly added [/api/v1alpha/logs/{job_id} endpoint](https://github.com/renderedtext/alles/pull/1403).
=> fix: use new logs endpoint

api/client/pipelines_v1_alpha.go, api/client/workflows_v1_alpha.go, cmd/get.go, cmd/get_test.go, cmd/pipelines/get.go, cmd/workflows/get.go
https://github.com/renderedtext/tasks/issues/6961
For old projects with lots and lots of pipelines/workflows, listing those resources can take quite some time.
Make use of the `created_after` and `created_before` arguments in these APIs:
- By default, list resources created in the last 3 months.
- Allow the user to override those defaults by using the `--age` argument.
=> feat: expose creation timestamp filters for pipelines/workflows

api/client/base_client.go, api/client/notifications_v1_alpha.go, api/models/notification_list_v1_alpha.go, cmd/get.go, cmd/get_notification.go, cmd/get_notification_test.go
**Issue:**  
[`sem get notifications`](https://github.com/renderedtext/tasks/issues/7499) does not currently support pagination or page size configuration, limiting results to a maximum of 100 entries.  
**Solution:**  
- The default behavior of `sem get notifications` is to iterate through all result pages and retrieve all notifications.
- Introduced `--page-size` (`-s`) to specify the number of results per page (up to 300).  
- Added `--page-token` (`-t`) to allow navigation through pages.  
- The response now includes a "Next page token" for fetching subsequent results.  
**Example Usage:**  
```sh
sem get notifications
```
**Output:**
```sh
NAME        AGE
test-1      2d
test-10     2d
test-100    2d
test-1000   2d
test-101    2d
test-102    2d
test-103    2d
...
test-993    2d …
```
=> feat: page size and pagination for get notifications cmd

.semaphore/semaphore.yml, Makefile
Uses security toolbox from public semaphoreio/semaphore repo
=> chore: use security-toolbox from public monorepo
